### ISSUE TITLE
Syntax highlighting is broken when using frontmatter (after upgrading to VS Code 1.92)

### ISSUE THREAD

**Issue by eminos** [Stillat/vscode-antlers-language-server#94]
**Describe the bug**
Seems the syntax highlighting is somewhat broken after upgrading to VS Code 1.92.
Having a frontmatter on the antlers file breaks the syntax highlighting. Or to be more precise, having more then one line

This works:
![image](https://github.com/user-attachments/assets/93521e0d-28bd-49e9-b8ce-afeed8fc48f5)

This breaks it:
![image](https://github.com/user-attachments/assets/7e176556-fc45-4476-9765-9e2d14e0ef28)

**Impacted Products**
Antlers Toolbox for VS Code

**Versions and Other Plugins/Extensions**
VS Code 1.92.0
Antlers Toolbox v2.6.19

**Comment by eminos** [comment]
Removed a few unrelated extensions, restarted VS Code, and now it's all back to normal...
Seems to have updated VS Code to 1.92.1 as well.
I have non idea what actually solved it.
It has probably nothing to do with this extension 🙂

**Comment by JohnathonKoster** [comment]
Interesting! Thanks for updating the issue, though 🙏

**Comment by RedCMD** [comment]
caused by https://github.com/microsoft/vscode/pull/219833

you will need to update your `frontMatter` intergration to something like https://github.com/microsoft/vscode-markdown-tm-grammar/pull/162
https://github.com/Stillat/vscode-antlers-language-server/blob/157d0eac3de834662d8616fdc828f554b8a73095/client/syntaxes/antlers.json#L123-L132

before VSCode re-adds the new YAML grammar again

related: https://github.com/microsoft/vscode/issues/224862

**Comment by JohnathonKoster** [comment]
Thank you for the extra info!
